// =================================================================================
// File:         7_vm_template/app/layout.tsx
// Version:      2.0
//
// Purpose:      This is the root layout for the Next.js application.
//
// V2.0 Change:  - CRITICAL FIX: Corrected the import path for the global
//                 stylesheet from "./globals.css" to "./global.css" to match
//                 the actual filename and resolve the "Module not found" error.
// =================================================================================
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css"; // FIX: Corrected filename from 'globals.css' to 'global.css'

const inter = Inter({ subsets: ["latin"] });

// Defines the default metadata for the application (e.g., for the browser tab title)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
